// packages/frontend/src/App.tsx
import React, { useState } from 'react';
import CodeEditor from './components/CodeEditor';
import SubmissionPanel from './components/SubmissionPanel';
import { SupportedLanguage } from '@letscode/shared';
import './App.css';

function App() {
  const [code, setCode] = useState('// Write your code here\n');
  const [language, setLanguage] = useState<SupportedLanguage>('javascript');
  const [submissionId, setSubmissionId] = useState<string | null>(null);

  const handleSubmit = async () => {
    try {
      const response = await fetch('http://localhost:3000/api/submit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          code,
          language,
          problemId: 'demo-problem',
          userId: 'demo-user',
          isCustomTest: false,
        }),
      });

      const data = await response.json();
      setSubmissionId(data.submissionId);
    } catch (error) {
      console.error('Submission failed:', error);
    }
  };

  return (
    <div className="app">
      <header className="app-header">
        <h1>Let'sCode Execution Engine</h1>
        <p>Innovative code execution with client-side, serverless, and hybrid strategies</p>
      </header>

      <div className="app-content">
        <div className="editor-section">
          <div className="editor-controls">
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value as SupportedLanguage)}
              className="language-select"
            >
              <option value="javascript">JavaScript</option>
              <option value="python">Python</option>
              <option value="cpp">C++</option>
              <option value="rust">Rust</option>
            </select>

            <button onClick={handleSubmit} className="submit-button">
              Submit Code
            </button>
          </div>

          <CodeEditor
            code={code}
            language={language}
            onChange={setCode}
          />
        </div>

        <div className="results-section">
          <SubmissionPanel submissionId={submissionId} />
        </div>
      </div>
    </div>
  );
}

export default App;

// packages/frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { ApiService } from './services/api.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  code = '// Write your code here\n';
  language: 'javascript' | 'python' | 'cpp' | 'rust' = 'javascript';
  submissionId: string | null = null;

  constructor(private apiService: ApiService) {}

  onCodeChange(code: string): void {
    this.code = code;
  }

  onLanguageChange(language: 'javascript' | 'python' | 'cpp' | 'rust'): void {
    this.language = language;
  }

  async submitCode(): Promise<void> {
    try {
      const response = await this.apiService.submitCode({
        code: this.code,
        language: this.language,
        problemId: 'demo-problem',
        userId: 'demo-user',
        isCustomTest: false
      });
      
      this.submissionId = response.submissionId;
    } catch (error) {
      console.error('Submission failed:', error);
    }
  }
}

<div class="app">
  <header class="app-header">
    <h1>Let'sCode Execution Engine</h1>
    <p>Innovative code execution with client-side, serverless, and hybrid strategies</p>
  </header>

  <div class="app-content">
    <div class="editor-section">
      <div class="editor-controls">
        <select 
          [(ngModel)]="language" 
          (change)="onLanguageChange(language)"
          class="language-select">
          <option value="javascript">JavaScript</option>
          <option value="python">Python</option>
          <option value="cpp">C++</option>
          <option value="rust">Rust</option>
        </select>

        <button (click)="submitCode()" class="submit-button">
          Submit Code
        </button>
      </div>

      <app-code-editor
        [code]="code"
        [language]="language"
        (codeChange)="onCodeChange($event)">
      </app-code-editor>
    </div>

    <div class="results-section">
      <app-submission-panel [submissionId]="submissionId"></app-submission-panel>
    </div>
  </div>
</div>
