// packages/frontend/src/components/SubmissionPanel.tsx
import React, { useEffect, useState } from 'react';
import { Submission } from '@letscode/shared';
import './SubmissionPanel.css';

interface SubmissionPanelProps {
  submissionId: string | null;
}

const SubmissionPanel: React.FC<SubmissionPanelProps> = ({ submissionId }) => {
  const [submission, setSubmission] = useState<Submission | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!submissionId) {
      setSubmission(null);
      return;
    }

    const fetchSubmission = async () => {
      setLoading(true);
      setError(null);

      try {
        const response = await fetch(`http://localhost:3000/api/submission/${submissionId}`);
        if (!response.ok) {
          throw new Error('Failed to fetch submission');
        }
        const data = await response.json();
        setSubmission(data);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    };

    fetchSubmission();
    const interval = setInterval(fetchSubmission, 2000);

    return () => clearInterval(interval);
  }, [submissionId]);

  if (!submissionId) {
    return (
      <div className="submission-panel">
        <div className="empty-state">
          <p>Submit your code to see results</p>
        </div>
      </div>
    );
  }

  if (loading && !submission) {
    return (
      <div className="submission-panel">
        <div className="loading">Loading...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="submission-panel">
        <div className="error">Error: {error}</div>
      </div>
    );
  }

  if (!submission) {
    return null;
  }

  return (
    <div className="submission-panel">
      <div className="panel-header">
        <h2>Submission Results</h2>
        <span className={`status-badge status-${submission.status.toLowerCase()}`}>
          {submission.status}
        </span>
      </div>

      <div className="panel-content">
        <div className="info-section">
          <div className="info-item">
            <span className="label">ID:</span>
            <span className="value">{submission.id.substring(0, 8)}...</span>
          </div>
          <div className="info-item">
            <span className="label">Language:</span>
            <span className="value">{submission.language}</span>
          </div>
          <div className="info-item">
            <span className="label">Strategy:</span>
            <span className="value">{submission.executionStrategy.type}</span>
          </div>
        </div>

        {submission.verdict && (
          <div className="verdict-section">
            <h3>Verdict</h3>
            <div className={`verdict verdict-${submission.verdict.status.toLowerCase().replace(/\s+/g, '-')}`}>
              {submission.verdict.status}
            </div>
            <div className="verdict-details">
              <div className="detail-item">
                <span className="label">Tests Passed:</span>
                <span className="value">
                  {submission.verdict.passedTests} / {submission.verdict.totalTests}
                </span>
              </div>
              <div className="detail-item">
                <span className="label">Max Time:</span>
                <span className="value">{submission.verdict.maxTime}ms</span>
              </div>
              <div className="detail-item">
                <span className="label">Max Memory:</span>
                <span className="value">
                  {(submission.verdict.maxMemory / 1024 / 1024).toFixed(2)}MB
                </span>
              </div>
            </div>
          </div>
        )}

        {submission.testResults && submission.testResults.length > 0 && (
          <div className="test-results-section">
            <h3>Test Cases</h3>
            {submission.testResults.map((result, index) => (
              <div key={index} className={`test-case ${result.passed ? 'passed' : 'failed'}`}>
                <div className="test-header">
                  <span>Test Case {result.testCaseNumber}</span>
                  <span className={`test-verdict ${result.passed ? 'passed' : 'failed'}`}>
                    {result.verdict}
                  </span>
                </div>
                <div className="test-details">
                  <span>Time: {result.executionTime}ms</span>
                  <span>Memory: {(result.memoryUsed / 1024 / 1024).toFixed(2)}MB</span>
                </div>
                {result.error && <div className="test-error">{result.error}</div>}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default SubmissionPanel;

// packages/frontend/src/app/components/submission-panel/submission-panel.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { interval, Subscription } from 'rxjs';
import { switchMap } from 'rxjs/operators';
import { ApiService } from '../../services/api.service';

interface Submission {
  id: string;
  status: string;
  language: string;
  executionStrategy: {
    type: string;
  };
  verdict?: {
    status: string;
    passedTests: number;
    totalTests: number;
    maxTime: number;
    maxMemory: number;
  };
  testResults?: Array<{
    testCaseNumber: number;
    passed: boolean;
    verdict: string;
    executionTime: number;
    memoryUsed: number;
    error?: string;
  }>;
}

@Component({
  selector: 'app-submission-panel',
  templateUrl: './submission-panel.component.html',
  styleUrls: ['./submission-panel.component.css']
})
export class SubmissionPanelComponent implements OnInit, OnDestroy {
  @Input() submissionId: string | null = null;
  
  submission: Submission | null = null;
  loading = false;
  error: string | null = null;
  private pollSubscription?: Subscription;

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    if (this.submissionId) {
      this.startPolling();
    }
  }

  ngOnChanges(): void {
    if (this.submissionId) {
      this.startPolling();
    } else {
      this.stopPolling();
      this.submission = null;
    }
  }

  ngOnDestroy(): void {
    this.stopPolling();
  }

  private startPolling(): void {
    this.stopPolling();
    this.loading = true;
    this.error = null;

    this.pollSubscription = interval(2000)
      .pipe(
        switchMap(() => this.apiService.getSubmission(this.submissionId!))
      )
      .subscribe({
        next: (submission) => {
          this.submission = submission;
          this.loading = false;
          
          if (submission.status === 'Completed' || submission.status === 'Failed') {
            this.stopPolling();
          }
        },
        error: (err) => {
          this.error = err.message || 'Failed to fetch submission';
          this.loading = false;
          this.stopPolling();
        }
      });
  }

  private stopPolling(): void {
    if (this.pollSubscription) {
      this.pollSubscription.unsubscribe();
      this.pollSubscription = undefined;
    }
  }

  formatMemory(bytes: number): string {
    return (bytes / 1024 / 1024).toFixed(2) + 'MB';
  }
}

<div class="submission-panel">
  <div *ngIf="!submissionId" class="empty-state">
    <p>Submit your code to see results</p>
  </div>

  <div *ngIf="loading && !submission" class="loading">
    Loading...
  </div>

  <div *ngIf="error" class="error">
    Error: {{ error }}
  </div>

  <div *ngIf="submission" class="panel-content">
    <div class="panel-header">
      <h2>Submission Results</h2>
      <span [class]="'status-badge status-' + submission.status.toLowerCase()">
        {{ submission.status }}
      </span>
    </div>

    <div class="info-section">
      <div class="info-item">
        <span class="label">ID:</span>
        <span class="value">{{ submission.id.substring(0, 8) }}...</span>
      </div>
      <div class="info-item">
        <span class="label">Language:</span>
        <span class="value">{{ submission.language }}</span>
      </div>
      <div class="info-item">
        <span class="label">Strategy:</span>
        <span class="value">{{ submission.executionStrategy.type }}</span>
      </div>
    </div>

    <div *ngIf="submission.verdict" class="verdict-section">
      <h3>Verdict</h3>
      <div [class]="'verdict verdict-' + submission.verdict.status.toLowerCase().replace(/\\s+/g, '-')">
        {{ submission.verdict.status }}
      </div>
      <div class="verdict-details">
        <div class="detail-item">
          <span class="label">Tests Passed:</span>
          <span class="value">
            {{ submission.verdict.passedTests }} / {{ submission.verdict.totalTests }}
          </span>
        </div>
        <div class="detail-item">
          <span class="label">Max Time:</span>
          <span class="value">{{ submission.verdict.maxTime }}ms</span>
        </div>
        <div class="detail-item">
          <span class="label">Max Memory:</span>
          <span class="value">{{ formatMemory(submission.verdict.maxMemory) }}</span>
        </div>
      </div>
    </div>

    <div *ngIf="submission.testResults && submission.testResults.length > 0" class="test-results-section">
      <h3>Test Cases</h3>
      <div *ngFor="let result of submission.testResults" 
           [class]="'test-case ' + (result.passed ? 'passed' : 'failed')">
        <div class="test-header">
          <span>Test Case {{ result.testCaseNumber }}</span>
          <span [class]="'test-verdict ' + (result.passed ? 'passed' : 'failed')">
            {{ result.verdict }}
          </span>
        </div>
        <div class="test-details">
          <span>Time: {{ result.executionTime }}ms</span>
          <span>Memory: {{ formatMemory(result.memoryUsed) }}</span>
        </div>
        <div *ngIf="result.error" class="test-error">{{ result.error }}</div>
      </div>
    </div>
  </div>
</div>
