// packages/frontend/src/app/components/code-editor/code-editor.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-code-editor',
  templateUrl: './code-editor.component.html',
  styleUrls: ['./code-editor.component.css']
})
export class CodeEditorComponent {
  @Input() code: string = '';
  @Input() language: string = 'javascript';
  @Output() codeChange = new EventEmitter<string>();

  editorOptions = {
    theme: 'vs-dark',
    language: 'javascript',
    minimap: { enabled: true },
    fontSize: 14,
    lineNumbers: 'on',
    roundedSelection: false,
    scrollBeyondLastLine: false,
    automaticLayout: true,
    tabSize: 2
  };

  ngOnChanges(): void {
    this.editorOptions = {
      ...this.editorOptions,
      language: this.getMonacoLanguage(this.language)
    };
  }

  onCodeChange(code: string): void {
    this.codeChange.emit(code);
  }

  private getMonacoLanguage(lang: string): string {
    const languageMap: { [key: string]: string } = {
      'javascript': 'javascript',
      'python': 'python',
      'cpp': 'cpp',
      'rust': 'rust'
    };
    return languageMap[lang] || 'javascript';
  }
}

<ngx-monaco-editor
  [options]="editorOptions"
  [(ngModel)]="code"
  (ngModelChange)="onCodeChange($event)"
  style="height: 100%;">
</ngx-monaco-editor>

// packages/frontend/src/components/CodeEditor.tsx
import React from 'react';
import Editor from '@monaco-editor/react';
import { SupportedLanguage } from '@letscode/shared';

interface CodeEditorProps {
  code: string;
  language: SupportedLanguage;
  onChange: (value: string) => void;
}

const languageMap: Record<SupportedLanguage, string> = {
  javascript: 'javascript',
  python: 'python',
  cpp: 'cpp',
  rust: 'rust',
};

const CodeEditor: React.FC<CodeEditorProps> = ({ code, language, onChange }) => {
  return (
    <Editor
      height="100%"
      language={languageMap[language]}
      value={code}
      onChange={(value) => onChange(value || '')}
      theme="vs-dark"
      options={{
        minimap: { enabled: true },
        fontSize: 14,
        lineNumbers: 'on',
        roundedSelection: false,
        scrollBeyondLastLine: false,
        automaticLayout: true,
        tabSize: 2,
      }}
    />
  );
};

export default CodeEditor;
